version: "3.7"

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: prisma-postgres 
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=danilo
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=meubanco
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data


volumes:
  postgres-data:
